"""inicial

Revision ID: 0c1838247ec6
Revises: 
Create Date: 2026-05-23 16:53:04.672991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1838247ec6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partidos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom_partido', sa.String(), nullable=False),
    sa.Column('fecha_partido', sa.DateTime(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidos_id'), 'partidos', ['id'], unique=False)
    op.create_table('pronosticos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_partido', sa.String(), nullable=True),
    sa.Column('pronostico_1', sa.Integer(), nullable=True),
    sa.Column('pronostico_2', sa.Integer(), nullable=True),
    sa.Column('participante', sa.String(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_partido'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participante', 'id_partido', name='uq_pronostico_participante_partido')
    )
    op.create_index(op.f('ix_pronosticos_id'), 'pronosticos', ['id'], unique=False)
    op.create_table('resultados_partidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_partido', sa.String(), nullable=True),
    sa.Column('resultado_1', sa.Integer(), nullable=True),
    sa.Column('resultado_2', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_partido'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_partido', name='uq_resultados_partidos')
    )
    op.create_index(op.f('ix_resultados_partidos_id'), 'resultados_partidos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_partidos_id'), table_name='resultados_partidos')
    op.drop_table('resultados_partidos')
    op.drop_index(op.f('ix_pronosticos_id'), table_name='pronosticos')
    op.drop_table('pronosticos')
    op.drop_index(op.f('ix_partidos_id'), table_name='partidos')
    op.drop_table('partidos')
    # ### end Alembic commands ###
